server: # REST and WS server
  port: 80 # you can change this if u want
  address: node.lewdhutao.my.eu.org #you can change this too
spring:
  main:
    banner-mode: log
lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: false
      soundcloud: false
      twitch: false
      vimeo: false
      mixer: false
      http: false
      local: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
tags:
some_key: some_value
another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 100MB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO